spring:
  datasource:
    url: jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=DB_N20;trustServerCertificate=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      username: sa
      password: johnswk17
      minimum-idle: 5  # ????????
      idle-timeout: 600000 # ?????????????600000?10???
      maximum-pool-size: 50 # ????????,???10
      auto-commit: true # ?????????????????????,????true
      pool-name: MyHikariCP # ?????
      max-lifetime: 1800000 # ????????????????,?0????????,??1800000?30??
      connection-timeout: 60000 # ?????????,??30?,?30000
  application:
    name: nextal
  jpa:
    #show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #database-platform: org.hibernate.dialect.SQLServer2008Dialect #???????  ??????? MySQL5InnoDBDialect ?????????InnoDB  ;????MySQLDialect ?????MyISAM
    database-platform: org.hibernate.dialect.SQLServerDialect
server:
  servlet:
    context-path: /nextal
  port: 8080

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.blanink.nextal.dao: info

